# Generated by Django 5.1.2 on 2024-10-09 14:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('classroom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'ADMIN'), ('student', 'STUDENT'), ('institution_owner', 'INSTITUTION_OWNER'), ('tutor', 'TUTOR'), ('moderator', 'MODERATOR'), ('teacher', 'TEACHER'), ('counselor', 'COUNSELOR'), ('administrator', 'ADMINISTRATOR'), ('librarian', 'LIBRARIAN'), ('it_staff', 'IT_STAFF'), ('alumni', 'ALUMNI'), ('guest_lecturer', 'GUEST_LECTURER'), ('mentor', 'MENTOR'), ('research_partner', 'RESEARCH_PARTNER'), ('government_agency', 'GOVERNMENT_AGENCY'), ('other', 'OTHER')], default='other', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('relationship', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')], max_length=20)),
                ('emergency_contact', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('qualifications', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('graduation_year', models.DateField()),
                ('degree', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialization', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('qualifications', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentAgency',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agency_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='GuestLecturer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject_specialization', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('qualifications', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_app.institution')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.title')),
            ],
        ),
        migrations.CreateModel(
            name='ITStaff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('qualifications', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experience', models.TextField()),
                ('qualifications', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experience', models.TextField()),
                ('qualifications', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPartner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization', models.CharField(max_length=255)),
                ('research_interests', models.TextField()),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('parent_permission', models.BooleanField(default=False)),
                ('grade_level', models.CharField(choices=[('Elementary', 'Elementary'), ('Middle School', 'Middle School'), ('High School', 'High School'), ('College', 'College')], max_length=20)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.parent')),
                ('subjects_of_interest', models.ManyToManyField(blank=True, to='classroom_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject_specialization', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('qualifications', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('description', models.TextField()),
                ('availability', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profile_picture', models.ImageField(upload_to='tutor_profiles')),
                ('background_check', models.TextField()),
                ('references', models.TextField()),
                ('institutions', models.ManyToManyField(blank=True, to='classroom_app.institution')),
                ('subjects', models.ManyToManyField(to='classroom_app.subject')),
            ],
        ),
    ]
