# Generated by Django 5.2.8 on 2025-11-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('classroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='counselor',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='governmentagency',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='guestlecturer',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='institutionalowner',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insitution_in_institution_owner', to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='institutionalowner',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.title'),
        ),
        migrations.AddField(
            model_name='itstaff',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='librarian',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='researchpartner',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='student',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects_of_interest',
            field=models.ManyToManyField(blank=True, to='classroom_app.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institutions',
            field=models.ManyToManyField(blank=True, to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='insitution_in_tutor', to='classroom_app.institution'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(to='classroom_app.subject'),
        ),
    ]
