# Generated by Django 5.1.2 on 2024-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='student_profiles'),
            preserve_default=False,
        ),
    ]
