# Generated by Django 5.1.2 on 2025-04-20 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_profile_picture'),
        ('classroom_app', '0004_classroom_created_by_classroom_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalowner',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insitution_in_institution_owner', to='classroom_app.institution'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='insitution_in_tutor', to='classroom_app.institution'),
        ),
    ]
