# Generated by Django 5.1 on 2025-06-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='student_profiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='state',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
