# Generated by Django 5.1 on 2025-06-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_teacher_address_teacher_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalowner',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.title'),
        ),
    ]
