# Generated by Django 5.1.2 on 2025-04-28 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_institutionalowner_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
