# Generated by Django 5.2.8 on 2026-08-20 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom_app', '0002_jobvacancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journey_type', models.CharField(choices=[('institutional', 'Institutional'), ('self_directed', 'Self-Directed')], default='institutional', max_length=20)),
                ('title', models.CharField(help_text="Human-readable label, e.g. 'Greenfield Secondary School' or 'Self-Directed: Python Fundamentals'.", max_length=255)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_journeys', to='classroom_app.institution')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='nkowe_core.learneridentity')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('provenance', models.CharField(choices=[('verified_institutional', 'Verified institutional data'), ('legacy_import', 'Legacy import (date approximate)'), ('self_reported', 'Self-reported')], default='verified_institutional', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classroom_app.institution')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='nkowe_core.learningjourney')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LearnerRecordEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_app', models.CharField(choices=[('exam_app', 'Exam App'), ('classroom_app', 'Classroom App'), ('library_app', 'Library App'), ('nkowe_core', 'Nkowe Core')], max_length=50)),
                ('event_type', models.CharField(help_text="e.g. 'exam_attempt_completed', 'assignment_completed'.", max_length=100)),
                ('provenance_category', models.CharField(choices=[('fact', 'Fact'), ('observation', 'Observation'), ('inference', 'Inference'), ('recommendation', 'Recommendation')], default='fact', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(help_text='When the underlying thing happened, not when this row was written.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_events', to='nkowe_core.enrollment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_events', to='nkowe_core.learneridentity')),
                ('responsible_actor', models.ForeignKey(blank=True, help_text='Who/what produced this event — the learner themself, a teacher, or null for system-generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['learner', '-occurred_at'], name='nkowe_core__learner_59c7eb_idx')],
            },
        ),
    ]
