# Generated by Django 5.2.8 on 2026-01-10 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(blank=True, related_name='collections', to='library_app.book')),
                ('owner', models.ForeignKey(help_text='The user who owns this collection', on_delete=django.db.models.deletion.CASCADE, related_name='owned_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
