# Generated by Django 5.2.8 on 2026-01-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_librarycollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycollection',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='public', help_text='Who can see this collection: public, private, or unlisted (default: public)', max_length=10),
        ),
    ]
