# Generated by Django 5.2.8 on 2026-01-10 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_librarycollection_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='A score/ranking for the recommendation (higher is more strongly recommended)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(help_text='The recommended book', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to_users', to='library_app.book')),
                ('user', models.ForeignKey(help_text='The user for whom these recommendations are generated', on_delete=django.db.models.deletion.CASCADE, related_name='book_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
