# Generated by Django 5.2.8 on 2026-01-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_bookrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True, help_text='The date and time when the book was most recently read by the user')),
                ('book', models.ForeignKey(help_text='The book that was read', on_delete=django.db.models.deletion.CASCADE, related_name='recently_read_by_users', to='library_app.book')),
                ('user', models.ForeignKey(help_text='The user who recently read the book', on_delete=django.db.models.deletion.CASCADE, related_name='recently_read_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
