# Generated by Django 5.2.8 on 2026-01-04 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_answer_custom_id_choice_custom_id_exam_custom_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
