# Generated by Django 5.2.8 on 2026-01-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_choice_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='custom_id',
        ),
    ]
