# Generated by Django 5.2.8 on 2026-01-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_remove_choice_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comprehension_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
