# Generated by Django 5.1.2 on 2024-10-12 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0002_examinationtype_tag_classroom_classroomattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomTermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom_app.classroom')),
            ],
        ),
    ]
