# Generated by Django 5.1 on 2025-06-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0003_announcement_classroommessage_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
    ]
