# Generated by Django 5.1.2 on 2025-04-20 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0004_classroom_created_by_classroom_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examinationtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examinationtype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
