# Generated by Django 5.1.2 on 2025-04-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0005_examinationtype_created_at_examinationtype_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.ManyToManyField(to='classroom_app.subject'),
        ),
    ]
