# Generated by Django 5.1.2 on 2025-04-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0006_remove_classroom_subject_classroom_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='tag',
            field=models.ManyToManyField(to='classroom_app.tag'),
        ),
        migrations.DeleteModel(
            name='ClassroomTag',
        ),
    ]
