# Generated by Django 5.1.2 on 2025-04-20 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0007_classroom_tag_delete_classroomtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutiontype',
            name='description',
        ),
        migrations.AddField(
            model_name='institutiontype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutiontype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institutiontype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
