# Generated by Django 5.1.2 on 2025-04-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0008_remove_institutiontype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examinationtype',
            name='level',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examinationtype',
            name='region',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
