# Generated by Django 5.1.2 on 2025-04-28 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0009_examinationtype_description_examinationtype_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='classroomattachment',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='classroomexamination',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='classroomstudent',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='classroomtermsandconditions',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='classroomtutor',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='examinationtype',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='institutiontype',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
