# Generated by Django 5.1.2 on 2025-04-28 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_app', '0010_classroom_custom_id_classroomattachment_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
