"""
Django settings for nkowebe project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Add dotenv support for env vars
from urllib.parse import urlparse
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The previous hardcoded key was committed to source control and must be treated as
# permanently compromised. SECRET_KEY now MUST come from the environment. The fallback
# below only fires for local development and is intentionally obviously insecure so it
# can never be mistaken for a real key if it leaks into a deployed environment.
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-LOCAL-DEV-ONLY-set-DJANGO_SECRET_KEY-env-var-for-real-use',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False now; set DJANGO_DEBUG=True explicitly in your local .env for development.
DEBUG = os.getenv('DJANGO_DEBUG', 'False').strip().lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    '.vercel.app',
    '127.0.0.1',
    'nkowebe.onrender.com',
    'localhost',
    'nkowe.vercel.app',   # <-- Added this to explicitly allow the correct Vercel frontend origin
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # installed libraries
    'drf_yasg',
    'import_export',
    'rest_framework',
    'rest_framework.authtoken',
    'allauth',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'corsheaders',
    "channels",

    # apps
    'account',
    'classroom_app',
    'chat_app',
    'exam_app',
    'library_app',
    'notebook_app',
    'drives_app',
    # New Nkowe Core domain layer (LearnerIdentity, LearningJourney,
    # Enrollment, LearnerRecordEvent) — additive, strangler-fig migration
    # target. See nkowe_core/models.py and the forensic audit §10-16.
    'nkowe_core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nkowebe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nkowebe.wsgi.application'

# ASGI_APPLICATION tells Channels (and `manage.py runserver`, once the
# `channels` app is installed) which application to route through for
# WebSocket support. Production already runs correctly today because the
# PROCFILE invokes Daphne directly against nkowebe.asgi:application, but
# leaving this unset broke local development: `python manage.py runserver`
# would never route /ws/... connections to Channels at all.
ASGI_APPLICATION = "nkowebe.asgi.application"

# Channel layer: uses Redis when REDIS_URL is configured, otherwise falls
# back to the in-process layer for local development.
#
# InMemoryChannelLayer only delivers group_send() messages to consumers
# connected to the SAME process. That's fine for a single local dev
# process, but it silently breaks cross-user delivery (chat messages,
# friend-request notifications, classroom announcements) the moment
# production runs more than one worker process, since two users connected
# to different processes can never reach each other — with no error, just
# messages that never arrive. Set REDIS_URL in production before scaling
# past a single web process.
REDIS_URL = os.getenv('REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    'account.auth_backends.UsernameOrEmailBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Add REST framework settings for TokenAuthentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # SECURITY: default-deny. Previously unset, which meant DRF's own default
    # (AllowAny) applied to any viewset that forgot to set permission_classes —
    # this is how several endpoints (custom-users, questions, exam attempts,
    # books, members, loans, etc.) ended up world-readable/writable with no
    # authentication at all. Every view that must be public now sets
    # permission_classes = [AllowAny] explicitly, so it's an intentional,
    # visible choice rather than an accident.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use DATABASE_URL from .env (see file_context_0)
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL and DATABASE_URL.startswith("postgres"):
    parsed = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path.lstrip('/'),
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': str(parsed.port) if parsed.port else '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = False

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "https://nkowebe.onrender.com",
    "https://nkowebe.vercel.app",
    "https://nkowe.vercel.app",   # <-- Added correct frontend origin that was blocked
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
    r"^https://nkowebe\.onrender\.com$",
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    # any others you need
]

# Enable HTTP & HTTPS CORS scheme
CORS_URLS_REGEX = r"^/.*$"

AUTH_USER_MODEL = 'account.CustomUser'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),  # This is for development use
# ]

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For production use

STATICFILES_DIR = os.path.join(BASE_DIR, "staticfiles")
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_DIR = os.path.join(BASE_DIR, "static")

# Ensure you also have this for serving static files in production
if not DEBUG:
    from django.contrib.staticfiles.storage import ManifestStaticFilesStorage
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# All auth

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'your_google_client_id'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'your_google_client_secret'

SOCIAL_AUTH_TWITTER_OAUTH_TOKEN = 'your_twitter_consumer_key'
SOCIAL_AUTH_TWITTER_OAUTH_TOKEN_SECRET = 'your_twitter_consumer_secret'

SOCIAL_AUTH_FACEBOOK_OAUTH2_KEY = 'your_facebook_client_id'
SOCIAL_AUTH_FACEBOOK_OAUTH2_SECRET = 'your_facebook_client_secret'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time',
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'en_US',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    },
    'twitter': {
        'SCOPE': ['email']
    }
}
